#!/bin/bash




################################################################

# Author: Olajutemo Timilehin
# Date: May 31st 2025
#
# Version: v1
#
# This script will report the aws resource usage

###############################################################




# list s3 buckets
echo "=================List of s3 buckets===================="
aws s3 ls

# list EC2 instances
echo "=================List of ec2 Instances===================="
aws ec2 describe-instances | jq ".Reservations[].Instances[].InstanceId" >> resourecTracker

# list lambda Functions
echo "=================List of Lambda functions===================="
aws lambda list-functions

#list IAM users
echo "=================List of IAM Users===================="
aws iam list-users
